---
language: python
services: docker

env:
    global:
    - ROLE_NAME: my-DRP

install:
    # Install test dependencies.
    - pip install ansible ansible-lint docker

script:
    # Run tests.
    - ansible-lint site.yml

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
