---
- name: Docker Apt Repo Key
  apt_key:
    url: https://download.docker.com/linux/raspbian/gpg
    state: present

- name: add Docker repo
  apt_repository:
    repo: deb https://download.docker.com/linux/raspbian/ buster stable
    state: present
    filename: docker-ce

- name: Install docker-ce without dependencies
  apt:
    update_cache: True
    install_recommends: no
    state: present
    name:
      - 'docker-ce'

- name: Install packages
  apt:
    state: present
    update_cache: True
    name:
      - 'git'
      - 'git-core'
      - 'wget'
      - 'tree'
      - 'curl'
      - 'firefox'
      - 'vim'
      - 'net-tools'
      - 'python3-pip'

- name: Modify User Arcones
  user:
    name: arcones
    comment: Marta Arcones
    shell: /bin/bash
    groups: sudo, docker
    append: yes

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "/home/arcones/Projects/Personal"
    - "/home/arcones/Projects/Professional"

# - name: Manage dotfiles
#   copy:
#     src: files/{{ item }}
#     dest: /home/arcones/{{ item }}
#     mode: 0644
#     owner: arcones
#     group: arcones
#   with_items:
#     - ".vimrc"
